from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet


def generate_report(filename, data):

    styles = getSampleStyleSheet()

    pdf = SimpleDocTemplate(filename)

    story = []

    story.append(Paragraph("<b>HireHive Placement Report</b>", styles["Title"]))

    story.append(Paragraph(f"Age : {data['Age']}", styles["Normal"]))
    story.append(Paragraph(f"Gender : {data['Gender']}", styles["Normal"]))
    story.append(Paragraph(f"Degree : {data['Degree']}", styles["Normal"]))
    story.append(Paragraph(f"Branch : {data['Branch']}", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph(f"Prediction : {data['Prediction']}", styles["Heading2"]))

    story.append(Paragraph(f"Placement Probability : {data['Probability']:.2f}%", styles["Normal"]))

    story.append(Paragraph("<br/><b>Recommended Companies</b>", styles["Heading2"]))

    for company in data["Companies"]:
        story.append(Paragraph(company, styles["Normal"]))

    story.append(Paragraph("<br/><b>Career Suggestions</b>", styles["Heading2"]))

    for tip in data["Suggestions"]:
        story.append(Paragraph(tip, styles["Normal"]))

    story.append(Paragraph("<br/>Generated by HireHive AI", styles["Italic"]))

    pdf.build(story)